Change to c++17 instead of c++14
This error occurred as exclusive scan wasn't supported on c++14 so needed to have c++17:
make[2]: *** [src/CMakeFiles/colmap.dir/ui/colormaps.cc.o] Error 4
In file included from /usr/local/include/ceres/ceres.h:67:0,
                 from /content/ceres-solver/build/colmap/src/estimators/pose.h:39,
                 from /content/ceres-solver/build/colmap/src/estimators/pose.cc:32:
/usr/local/include/ceres/product_manifold.h: In static member function ‘static std::array<T, N> ceres::ProductManifold<Manifold0, Manifold1, ManifoldN>::ExclusiveScan(const std::array<T, N>&)’:
/usr/local/include/ceres/product_manifold.h:260:10: error: ‘exclusive_scan’ is not a member of ‘std’
     std::exclusive_scan(values.begin(), values.end(), result.begin(), 0);